# Generated by Django 4.2 on 2023-05-31 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_alter_user_firstname_alter_user_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
