# Generated by Django 4.2 on 2023-06-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0006_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
