# Generated by Django 4.2 on 2023-06-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0007_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=False, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
