# Generated by Django 4.2 on 2023-06-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='genre',
            field=models.CharField(default='hi', max_length=255, verbose_name='genre'),
            preserve_default=False,
        ),
    ]
