# Generated by Django 4.2 on 2023-06-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_watchlist_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='genre',
        ),
    ]
