# Generated by Django 4.2 on 2023-06-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_remove_watchlist_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='movie',
            new_name='film',
        ),
    ]
