# Generated by Django 4.2 on 2023-06-25 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filmspage', '0001_initial'),
        ('genreslist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenresFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmspage.film')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genreslist.genreslist')),
            ],
        ),
    ]
