# Generated by Django 4.2 on 2023-05-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmspage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
