# Generated by Django 4.2 on 2023-05-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmspage', '0002_alter_film_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(upload_to='media/photos/'),
        ),
    ]
