# Generated by Django 4.2 on 2023-05-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmspage', '0004_alter_film_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(upload_to='D:/python_hilel/python_pro/Projects/IMDB/media/photo/'),
        ),
    ]
